version: '3.8'

services:
  cms-bundle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-bundle
    ports:
      - "${PORT:-3008}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
    volumes:
      # Mount bundle directory để lưu trữ các file bundle
      - ./bundle:/app/bundle
    restart: unless-stopped
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge

